import { Roboto, Playfair_Display } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Load local fonts as you did before
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Load Google Fonts
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-roboto",
});

const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-playfair-display",
});

export const metadata = {
  title: "www.impactforsuccessfoundation.org",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon/favicon-16x16.png" />
      <link rel="icon" href="/favicon/favicon-32x32.png" />
      <link rel="icon" href="/favicon/apple-touch-icon.png" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${playfairDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
